### ISSUE TITLE
Write Y.Handlebars view engine for Express 3.x

### ISSUE THREAD

**Issue by ericf** [ericf/photosnear.me#4]
Given the significant changes to how views and view engines are handled in Express 3.x, a specialized view engine needs to be created for `Y.Handlebars` which aids the sharing of templates between the server and browser.
### Requirements
- Works with vanilla Handlebars or `Y.Handlebars`.
- Has no dependencies.
- Fulfills Express.js' template adapter API.
- Respects caching for easy dev and make prod fast.
- Can expose precompiled templates.
- Supports concept of a wrapping `layout` template.
- Manages its own partials, and readies them before rendering.

**Comment by msaglietto** [comment]
Hello Eric, I was looking using something like https://github.com/visionmedia/consolidate.js to make the template engine .. but you lose the layouts ... 

I was writing a custom consolidate that load the layout first if exist but I'm not sure how was working and  how it know form where to read the layout and if is supposed to load the view template on the body.

**Comment by ericf** [comment]
@msaglietto Okay, I'd be interested to see what you come up with.

**Comment by msaglietto** [comment]
The basic was something like this https://gist.github.com/3790923

Then I tryed to add the layout and render the template on the body but I dont find where do i have the path to the layout

Here I made a commit in my fork if u want to see the whole change .. .

https://github.com/msaglietto/photosnear.me/commit/92d36e66a72222c5282634b074600ca046fb3983

**Comment by ericf** [comment]
Updated the issue description with a list of requirements.

**Comment by ericf** [comment]
Created [express3-handlebars](https://github.com/ericf/express3-handlebars) and published it as an npm module.
